### ISSUE TITLE
Exception raised when mutating pattern matching

### ISSUE THREAD

**Issue by HashNotAdam** [mbj/mutant#1417]
Given the following code:
```ruby
case some_method_call
in {result: true}
  success_thing
in {result: false, error:}
  failure_thing
end
```

I receive this error from mutant:
```
Killfork exited nonzero. Its result (if any) was ignored.
Process status:
#<Process::Status: pid 33464 exit 1>
Log messages (combined stderr and stdout):
[killfork] ...mutant-0.11.27/lib/mutant/loader.rb:30:in `eval': path_to_my_class.rb:28: syntax error, unexpected terminator, expecting literal content or tSTRING_DBEG or tSTRING_DVAR or tLABEL_END (SyntaxError)
[killfork]         in {%(): true} then
[killfork]               ^
[killfork] 
[killfork]      from ...mutant-0.11.27/lib/mutant/loader.rb:30:in `call'
[killfork]      from ...mutant-0.11.27/lib/mutant/loader.rb:19:in `call'
[killfork]      from ...mutant-0.11.27/lib/mutant/mutation.rb:67:in `insert'
[killfork]      from ...mutant-0.11.27/lib/mutant/env.rb:165:in `block in run_mutation_tests'
...
```

The subsequent diff looks like:
```ruby
   case some_method_call
-  in {result: true} then
+  in {%(): true} then
     success_thing
   in {result: false, error:} then
     failure_thing
   end
```

My stack is:

- mutant 0.11.27
- Ruby 3.3.0

**Comment by mbj** [comment]
@HashNotAdam Thanks for the report, fixed with v0.11.28 I have just released!
