### ISSUE TITLE
Could not use License due to HTTP 404  Not Found

### ISSUE THREAD

**Issue by visu-suganya** [mbj/mutant#1434]
The following is the `bundle install --verbose` output in my local machine
It seems error slightly different from the #964 issue [gist]
Please help us to complete this step. 

```
kuppusamy.suganya@Suganyas-MacBook-Air ruby_branch_coverage % bundle install --verbose
Running `bundle install --verbose` with bundler 2.4.7
Found changes from the lockfile, re-resolving dependencies because the list of sources changed, the dependencies in your gemfile changed, you added a new platform to your gemfile, the gemspecs for path gems changed
HTTP GET https://oss@gem.mutant.dev/versions
HTTP 404 Not Found https://oss@gem.mutant.dev/versions
Bundler::Fetcher::FallbackError: Net::HTTPNotFound: https://oss@gem.mutant.dev/versions
/Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/downloader.rb:45:in `fetch'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/compact_index.rb:124:in `call'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/compact_index_client/updater.rb:47:in `update'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/compact_index_client.rb:92:in `update'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/compact_index_client.rb:79:in `update_and_parse_checksums!'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/compact_index.rb:68:in `available?'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:158:in `use_api'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:395:in `block in api_fetchers'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:395:in `select'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:395:in `api_fetchers'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:295:in `dependency_api_available?'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:560:in `all?'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:560:in `precompute_source_requirements_for_indirect_dependencies?'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:844:in `source_requirements'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:497:in `resolution_packages'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:486:in `resolver'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:554:in `start_resolution'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:289:in `resolve'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:507:in `materialize'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:197:in `specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:83:in `block in run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `open'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `lock'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:71:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:23:in `install'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli/install.rb:62:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:261:in `block in install'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/settings.rb:131:in `temporary'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:260:in `install'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
HTTP GET https://oss@gem.mutant.dev/api/v1/dependencies
HTTP 404 Not Found https://oss@gem.mutant.dev/api/v1/dependencies
Fetching source index from https://gem.mutant.dev/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://gem.mutant.dev/ due to underlying error <bad response Not Found 404 (https://oss:REDACTED@gem.mutant.dev/specs.4.8.gz)>
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://gem.mutant.dev/ due to underlying error <bad response Not Found 404 (https://oss:REDACTED@gem.mutant.dev/specs.4.8.gz)>
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://gem.mutant.dev/ due to underlying error <bad response Not Found 404 (https://oss:REDACTED@gem.mutant.dev/specs.4.8.gz)>
Bundler::HTTPError: Could not fetch specs from https://gem.mutant.dev/ due to underlying error <bad response Not Found 404 (https://oss:REDACTED@gem.mutant.dev/specs.4.8.gz)>
/Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/index.rb:21:in `rescue in specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher/index.rb:8:in `specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:133:in `block in specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:132:in `drop_while'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:132:in `specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:119:in `block in specs_with_retry'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/retry.rb:40:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/retry.rb:30:in `attempt'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/fetcher.rb:118:in `specs_with_retry'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:424:in `block in fetch_names'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:417:in `each'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:417:in `fetch_names'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:403:in `block in remote_specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/index.rb:9:in `build'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:399:in `remote_specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:131:in `specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems_aggregate.rb:35:in `block (2 levels) in build_index'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems_aggregate.rb:33:in `each'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems_aggregate.rb:33:in `block in build_index'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/index.rb:9:in `build'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems_aggregate.rb:30:in `build_index'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/source/rubygems_aggregate.rb:12:in `initialize'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:849:in `new'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:849:in `source_requirements'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:497:in `resolution_packages'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:486:in `resolver'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:554:in `start_resolution'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:289:in `resolve'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:507:in `materialize'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/definition.rb:197:in `specs'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:83:in `block in run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `open'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/process_lock.rb:9:in `lock'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:71:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/installer.rb:23:in `install'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli/install.rb:62:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:261:in `block in install'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/settings.rb:131:in `temporary'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:260:in `install'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
  /Users/kuppusamy.suganya/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by visu-suganya** [comment]
@mbj please have a look on this issue, so that we can proceed further.
Thanks in advance.

**Comment by mbj** [comment]
@visu-suganya sorry for not reacting earlier, I was on vacation. It sounds you are good now?

**Comment by visu-suganya** [comment]
Hi @mbj Yes Its working fine now. Thank you.
