### ISSUE TITLE
Mutant not completing

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#229]
I was working through instrumenting tests this morning on a small routine and after numerous runs of mutant and reducing the alives I ended up in a scenario where mutant never completes. In running all the tests there were 232 mutations, and the kills + alives got to 231 total and then mutant would not finish. I was using -j8 which is evenly divisible into 232, so I changed it to -j3. Then the mutations - (kills + alives) ended up 2 away from completion before it froze. The CPU time continued to increase and CPU was at 100%. I then tried just the method that was running during the final mutations and that still caused it to spin. I let it run for a few minutes, and then killed it manually:

```
Matcher:            #<Mutant::Matcher::Config match_expressions=[<Mutant::Expression: ConstructionMonitor#add>] subject_ignores=[] subject_selects=[]>
Integration:        rspec
Expect Coverage:    100.00%
Processes:          3
Includes:           ["app/helpers"]
Requires:           ["./config/environment.rb", "construction_monitor.rb"]
Available Subjects: 1
Subjects:           1
Mutations:          101
Kills:              78
Alive:              21
Runtime:            53.13s
Killtime:           83.99s
Overhead:           -36.74%
Coverage:           78.79%
Expected:           100.00%
Active subjects:    1
ConstructionMonitor#add:/Users/tj/projects/AOT/aotv2/app/helpers/construction_monitor.rb:27 mutations: 101
- rspec:ConstructionMonitor
...............FF.F..........F...F..F.....F...FF.................................FFFFFFFFFFFF......
(78/101)  78% - killtime: 83.99s runtime: 118.67s overhead: 34.68s
load: 3.77  cmd: ruby 12723 running 58.57u 1.85s
load: 3.77  cmd: ruby 12723 running 59.03u 1.86s
load: 3.55  cmd: ruby 12723 running 60.08u 1.87s
load: 3.55  cmd: ruby 12723 running 61.56u 1.88s
load: 3.55  cmd: ruby 12723 running 63.02u 1.90s
load: 3.55  cmd: ruby 12723 running 63.97u 1.91s
load: 3.34  cmd: ruby 12723 running 64.35u 1.92s
load: 3.34  cmd: ruby 12723 running 65.74u 1.94s
load: 3.34  cmd: ruby 12723 running 67.66u 1.96s
load: 3.31  cmd: ruby 12723 running 69.99u 2.00s
load: 3.31  cmd: ruby 12723 running 72.62u 2.01s
load: 2.77  cmd: ruby 12723 running 438.73u 8.45s
^CParallel execution interrupted, exiting ...
Parallel execution interrupted, exiting ...
/Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:330:in `write': Broken pipe (Errno::EPIPE)
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:330:in `dump'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:330:in `process_incoming_jobs'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:309:in `block in worker'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:302:in `fork'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:302:in `worker'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:290:in `block in create_workers'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:289:in `each'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:289:in `create_workers'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:246:in `work_in_processes'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:118:in `map'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/isolation.rb:41:in `call'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:170:in `run_mutation_test'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:147:in `block in kill_mutation'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:146:in `each'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:146:in `each_with_object'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:146:in `kill_mutation'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:132:in `block in run_mutation'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/result.rb:66:in `compute'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:128:in `run_mutation'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:400:in `call'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:400:in `call_with_index'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:326:in `process_incoming_jobs'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:309:in `block in worker'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:302:in `fork'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:302:in `worker'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:290:in `block in create_workers'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:289:in `each'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:289:in `create_workers'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:246:in `work_in_processes'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/parallel-1.1.2/lib/parallel.rb:118:in `map'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:44:in `run'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/runner.rb:20:in `initialize'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/procto-0.0.2/lib/procto.rb:62:in `block in initialize'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/env.rb:40:in `run'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/procto-0.0.2/lib/procto.rb:62:in `public_send'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/gems/procto-0.0.2/lib/procto.rb:62:in `block in initialize'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/lib/mutant/cli.rb:25:in `run'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bundler/gems/mutant-967bafc8ee46/bin/mutant:19:in `<top (required)>'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bin/mutant:23:in `load'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bin/mutant:23:in `<main>'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/tj/.rvm/gems/ruby-2.1.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

After letting it run for a while that is the only trace I got. Each time prior I would see 2 "Parallel execution interrupted, exiting ..." messages each time I aborted. My inference (which is likely wrong) is it is hung waiting for the parallel worker threads to finish. 

I am going to leave this module alone for now in case there is more testing I should do. 

The method (unmutated) looks like:

```
  def add(base, query, text)
    content = query.map(&:id)
    @total += 100.0
    if content.any?
      @issues[text] = content
      @progress += (base - content.size) * 100.0 / base
    else
      @progress += 100.0
    end
  end
```

**Comment by mbj** [comment]
@tjchambers Also note mutant now can timeout mutations to infinite runtime by itself, and be configured to count such timeouts as covered: https://github.com/mbj/mutant/blob/master/docs/configuration.md#mutation_timeout
