### ISSUE TITLE
Mutant fails when tput binary is not present

### ISSUE THREAD

**Issue by dkubb** [mbj/mutant#520]
When the tput binary (from curse) is not present mutant will raise an error:

```
/usr/lib/ruby/gems/2.2.0/gems/activemerchant-1.44.1/lib/active_merchant/country.rb:62: warning: already initialized constant ActiveMerchant::Country::COUNTRIES
/usr/lib/ruby/gems/2.2.0/gems/active_utils-2.2.3/lib/active_utils/common/country.rb:65: warning: previous definition of COUNTRIES was here
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.4.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'mutant'.
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/opt/rails/config/application.rb:17:in `<top (required)>'
/opt/rails/Rakefile:1:in `require'
/opt/rails/Rakefile:1:in `<top (required)>'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>'
Errno::ENOENT: No such file or directory - tput
/usr/lib/ruby/2.2.0/open3.rb:193:in `spawn'
/usr/lib/ruby/2.2.0/open3.rb:193:in `popen_run'
/usr/lib/ruby/2.2.0/open3.rb:93:in `popen3'
/usr/lib/ruby/2.2.0/open3.rb:252:in `capture3'
/usr/lib/ruby/gems/2.2.0/bundler/gems/mutant-4f7df519ea43/lib/mutant/reporter/cli/tput.rb:40:in `capture'
/usr/lib/ruby/gems/2.2.0/bundler/gems/mutant-4f7df519ea43/lib/mutant/reporter/cli/tput.rb:20:in `detect'
/usr/lib/ruby/gems/2.2.0/bundler/gems/mutant-4f7df519ea43/lib/mutant/reporter/cli.rb:15:in `build'
/usr/lib/ruby/gems/2.2.0/bundler/gems/mutant-4f7df519ea43/lib/mutant.rb:202:in `<class:Config>'
/usr/lib/ruby/gems/2.2.0/bundler/gems/mutant-4f7df519ea43/lib/mutant.rb:191:in `<module:Mutant>'
/usr/lib/ruby/gems/2.2.0/bundler/gems/mutant-4f7df519ea43/lib/mutant.rb:189:in `<top (required)>'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/opt/rails/config/application.rb:17:in `<top (required)>'
/opt/rails/Rakefile:1:in `require'
/opt/rails/Rakefile:1:in `<top (required)>'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:23:in `load'
/usr/bin/rake:23:in `<main>’
```

**Comment by mbj** [comment]
Mutant only does check if the tput binary provides the expected operations, and does not anticipate it could be missing. In case of missing it should simply behave like the expected operations on the binary not being present.

**Comment by mbj** [comment]
Support for the so called "framed reporter" was removed, as it had also other various shortcommings. This also removed the use of `tput`.
