### ISSUE TITLE
Problem of running mutant on Rails application

### ISSUE THREAD

**Issue by Winbobob** [mbj/mutant#690]
Hi, I tried to use mutant on a [rails application](https://github.com/Automated-Program-Repair-in-Expertiza/mutant_rails_app) by following the [video](https://www.youtube.com/watch?v=G7c0_FlR-R4).

Basically it is a very simple rails application. And I try to run mutant by the command `RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec PostsController -j 1`. And I got an error
```
home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/mutant-rspec-0.8.8/lib/mutant/integration/rspec.rb:30:in `<class:Rspec>': undefined method `register' for Mutant::Integration::Rspec:Class (NoMethodError)
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/mutant-rspec-0.8.8/lib/mutant/integration/rspec.rb:20:in `<class:Integration>'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/mutant-rspec-0.8.8/lib/mutant/integration/rspec.rb:4:in `<module:Mutant>'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/mutant-rspec-0.8.8/lib/mutant/integration/rspec.rb:3:in `<top (required)>'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/lib/mutant/integration.rb:20:in `require'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/lib/mutant/integration.rb:20:in `setup'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/lib/mutant/cli.rb:103:in `setup_integration'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1396:in `call'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1396:in `block in parse_in_order'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
	from /home/expertiza_developer/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/lib/mutant/cli.rb:56:in `parse'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/lib/mutant/cli.rb:29:in `initialize'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/lib/mutant/cli.rb:15:in `run'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bundler/gems/mutant-7c3f3a5f5cef/bin/mutant:39:in `<top (required)>'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bin/mutant:23:in `load'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bin/mutant:23:in `<main>'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/expertiza_developer/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
```

And I went through the [source code](https://github.com/mbj/mutant/blob/0655c60beef20469c8b9328cdcc6ac6bfdafccc1/lib/mutant/integration/rspec.rb#L30) (`register 'rspec'`), but I did not know where this `register` method call from.

PS. I also read the recommended article `A deep dive into mutation testing and how the Mutant gem works`. It is really helpful. And I can run the `hello-world` example mentioned in the article successfully. However, the `hello-world` example is not a rails application.

I use `ruby-2.2.5` and `mutant-0.8.8` by the way. Could some one help me? Thank you in advance!

**Comment by Winbobob** [comment]
Yesterday I did not realize that `mutant` and `mutant-rspec` shared the same repo. When I changed the Gemfile as following, the error above is gone.
```
group :development, :test do
  gem 'mutant', :git => 'https://github.com/mbj/mutant.git'
  gem 'mutant-rspec', :git => 'https://github.com/mbj/mutant.git'
  gem 'test-unit'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'pry-byebug'
end
```

Now I got the error `/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in require': cannot load such file -- rspec/rails (LoadError)`. I am trying to fix it.

**Comment by Winbobob** [comment]
After I added `gem 'rspec-rails'` in Gemfile test group, mutant works!

**Comment by mbj** [comment]
> After I added gem 'rspec-rails' in Gemfile test group, mutant works!

This is not a mutant issue, more exposed a bug in your spec setup. Glad it works for you now. Feel free to PR a readme improvement if you think it could be better for your case. Happy mutating.
