### ISSUE TITLE
LoadError "mutant/mutator/node"

### ISSUE THREAD

**Issue by seza443** [mbj/mutant#702]
I'm trying to run `RAILS_ENV=test bundle exec mutant -r ./config/environment --use rspec User` on my Rails project but I get the error

```
/var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant.rb:91:in `require': cannot load such file -- mutant/mutator/node (LoadError)
	from /var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant.rb:91:in `<top (required)>'
	from /var/lib/gems/2.2.0/gems/mutant-0.8.12/bin/mutant:8:in `require'
	from /var/lib/gems/2.2.0/gems/mutant-0.8.12/bin/mutant:8:in `<top (required)>'
	from /usr/local/bin/mutant:23:in `load'
	from /usr/local/bin/mutant:23:in `<main>
```

Actually running `mutant` or `bundle exec mutant` give the same error 😞 

Any help would be great 😄 

> Ubuntu 16.04 64bits
> ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux-gnu]
> Rails 4.2.7.1
> mutant 0.8.12
> mutant-rspec 0.8.11

**Comment by mbj** [comment]
@seza443 Is `lib/mutant/muator/node.rb` present in your filesystem (relative to the mutant intstallation directory?

If not present: Your gem is corrupt.

If present: Rails inference via its crazy loading hacks.

**Comment by seza443** [comment]
$ bundle show mutant
      /var/lib/gems/2.2.0/gems/mutant-0.8.12

and then

    $ ls /var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant/mutator/node.rb 
      /var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant/mutator/node.rb

So yes it is indeed present.

To give a bit more details, I had the error when running Ubuntu in a VM.
But I succeed to run mutant on [Bash on Ubuntu on Windows](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

So not sure if you want to spend time on this issue or close it already 😃

**Comment by mbj** [comment]
@seza443 I'm fine to help you a bit on that one. 

Can you verify your `$LOAD_PATH` containts the mutant lib directory the time the logical require path `mutant/mutator/node` gets loaded?

You can inspect `$LOAD_PATH` just before the failing require happens.

**Comment by seza443** [comment]
Ok, I've added `print $LOAD_PATH` in the file `/var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant.rb` just before line 91

And running `bundle exec mutant` outputs:

```
["/var/lib/gems/2.2.0/gems/bundler-1.14.4/lib", "/var/lib/gems/2.2.0/gems/web-console-2.3.0/lib", "/var/lib/gems/2.2.0/gems/uglifier-3.0.4/lib", "/var/lib/gems/2.2.0/gems/tzinfo-data-1.2016.10/lib", "/var/lib/gems/2.2.0/gems/turbolinks-5.0.1/lib", "/var/lib/gems/2.2.0/gems/turbolinks-source-5.0.0/lib", "/var/lib/gems/2.2.0/gems/spring-2.0.1/lib", "/var/lib/gems/2.2.0/gems/shoulda-matchers-3.1.1/lib", "/var/lib/gems/2.2.0/gems/sdoc-0.4.2/lib", "/var/lib/gems/2.2.0/gems/sass-rails-5.0.6/lib", "/var/lib/gems/2.2.0/gems/tilt-2.0.6/lib", "/var/lib/gems/2.2.0/gems/sass-3.4.23/lib", "/var/lib/gems/2.2.0/gems/rspec-rails-3.5.2/lib", "/var/lib/gems/2.2.0/gems/rspec-mocks-3.5.0/lib", "/var/lib/gems/2.2.0/gems/rspec-expectations-3.5.0/lib", "/var/lib/gems/2.2.0/gems/rdoc-4.3.0/lib", "/var/lib/gems/2.2.0/gems/rails_12factor-0.0.3/lib", "/var/lib/gems/2.2.0/gems/rails_stdout_logging-0.0.5/lib", "/var/lib/gems/2.2.0/gems/rails_serve_static_assets-0.0.5/lib", "/var/lib/gems/2.2.0/gems/rack-cors-0.4.0/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/puma-3.7.0", "/var/lib/gems/2.2.0/gems/puma-3.7.0/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/pg-0.19.0", "/var/lib/gems/2.2.0/gems/pg-0.19.0/lib", "/var/lib/gems/2.2.0/gems/mutant-rspec-0.8.11/lib", "/var/lib/gems/2.2.0/gems/rspec-core-3.5.4/lib", "/var/lib/gems/2.2.0/gems/rspec-support-3.5.0/lib", "/var/lib/gems/2.2.0/gems/mutant-0.8.12/lib", "/var/lib/gems/2.2.0/gems/unparser-0.2.5/lib", "/var/lib/gems/2.2.0/gems/regexp_parser-0.3.6/lib", "/var/lib/gems/2.2.0/gems/parser-2.3.3.1/lib", "/var/lib/gems/2.2.0/gems/parallel-1.10.0/lib", "/var/lib/gems/2.2.0/gems/morpher-0.2.6/lib", "/var/lib/gems/2.2.0/gems/procto-0.0.3/lib", "/var/lib/gems/2.2.0/gems/jquery-rails-4.2.2/lib", "/var/lib/gems/2.2.0/gems/jbuilder-2.6.1/lib", "/var/lib/gems/2.2.0/gems/multi_json-1.12.1/lib", "/var/lib/gems/2.2.0/gems/factory_girl_rails-4.8.0/lib", "/var/lib/gems/2.2.0/gems/factory_girl-4.8.0/lib", "/var/lib/gems/2.2.0/gems/diff-lcs-1.2.5/lib", "/var/lib/gems/2.2.0/gems/devise_token_auth-0.1.40/lib", "/var/lib/gems/2.2.0/gems/rails-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/sprockets-rails-3.2.0/lib", "/var/lib/gems/2.2.0/gems/sprockets-3.7.1/lib", "/var/lib/gems/2.2.0/gems/devise-4.2.0/lib", "/var/lib/gems/2.2.0/gems/warden-1.2.7/lib", "/var/lib/gems/2.2.0/gems/responders-2.3.0/lib", "/var/lib/gems/2.2.0/gems/orm_adapter-0.5.0/lib", "/var/lib/gems/2.2.0/gems/concurrent-ruby-1.0.4/lib", "/var/lib/gems/2.2.0/gems/concord-0.1.5/lib", "/var/lib/gems/2.2.0/gems/coffee-rails-4.1.1/lib", "/var/lib/gems/2.2.0/gems/railties-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/thor-0.19.4/lib", "/var/lib/gems/2.2.0/gems/coffee-script-2.4.1/lib", "/var/lib/gems/2.2.0/gems/execjs-2.7.0/lib", "/var/lib/gems/2.2.0/gems/coffee-script-source-1.12.2/lib", "/var/lib/gems/2.2.0/gems/codeclimate-test-reporter-1.0.5/lib", "/var/lib/gems/2.2.0/gems/simplecov-0.13.0/lib", "/var/lib/gems/2.2.0/gems/simplecov-html-0.10.0/lib", "/var/lib/gems/2.2.0/gems/docile-1.1.5/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/byebug-9.0.6", "/var/lib/gems/2.2.0/gems/byebug-9.0.6/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/binding_of_caller-0.7.2", "/var/lib/gems/2.2.0/gems/binding_of_caller-0.7.2/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/debug_inspector-0.0.2", "/var/lib/gems/2.2.0/gems/debug_inspector-0.0.2/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/bcrypt-3.1.11", "/var/lib/gems/2.2.0/gems/bcrypt-3.1.11/lib", "/var/lib/gems/2.2.0/gems/ast-2.3.0/lib", "/var/lib/gems/2.2.0/gems/anima-0.3.0/lib", "/var/lib/gems/2.2.0/gems/equalizer-0.0.11/lib", "/var/lib/gems/2.2.0/gems/adamantium-0.2.0/lib", "/var/lib/gems/2.2.0/gems/memoizable-0.4.2/lib", "/var/lib/gems/2.2.0/gems/ice_nine-0.11.2/lib", "/var/lib/gems/2.2.0/gems/activerecord-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/arel-6.0.4/lib", "/var/lib/gems/2.2.0/gems/active_model_serializers-0.10.4/lib", "/var/lib/gems/2.2.0/gems/jsonapi-0.1.1.beta6/lib", "/var/lib/gems/2.2.0/gems/jsonapi-renderer-0.1.1.beta1/lib", "/var/lib/gems/2.2.0/gems/jsonapi-parser-0.1.1.beta3/lib", "/var/lib/gems/2.2.0/gems/case_transform-0.2/lib", "/var/lib/gems/2.2.0/gems/activemodel-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/actionmailer-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/mail-2.6.4/lib", "/var/lib/gems/2.2.0/gems/mime-types-3.1/lib", "/var/lib/gems/2.2.0/gems/mime-types-data-3.2016.0521/lib", "/var/lib/gems/2.2.0/gems/activejob-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/globalid-0.3.7/lib", "/var/lib/gems/2.2.0/gems/actionpack-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/rack-test-0.6.3/lib", "/var/lib/gems/2.2.0/gems/rack-1.6.5/lib", "/var/lib/gems/2.2.0/gems/actionview-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/rails-html-sanitizer-1.0.3/lib", "/var/lib/gems/2.2.0/gems/loofah-2.0.3/lib", "/var/lib/gems/2.2.0/gems/rails-dom-testing-1.0.8/lib", "/var/lib/gems/2.2.0/gems/rails-deprecated_sanitizer-1.0.3/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/nokogiri-1.7.0.1", "/var/lib/gems/2.2.0/gems/nokogiri-1.7.0.1/lib", "/var/lib/gems/2.2.0/gems/mini_portile2-2.1.0/lib", "/var/lib/gems/2.2.0/gems/erubis-2.7.0/lib", "/var/lib/gems/2.2.0/gems/builder-3.2.3/lib", "/var/lib/gems/2.2.0/gems/activesupport-4.2.7.1/lib", "/var/lib/gems/2.2.0/gems/tzinfo-1.2.2/lib", "/var/lib/gems/2.2.0/gems/thread_safe-0.3.5/lib", "/var/lib/gems/2.2.0/gems/minitest-5.10.1/lib", "/var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.6", "/var/lib/gems/2.2.0/gems/json-1.8.6/lib", "/var/lib/gems/2.2.0/gems/i18n-0.8.0/lib", "/var/lib/gems/2.2.0/gems/abstract_type-0.0.7/lib", "/var/lib/gems/2.2.0/gems/rake-12.0.0/lib", "/usr/local/lib/site_ruby/2.2.0", "/usr/local/lib/x86_64-linux-gnu/site_ruby", "/usr/local/lib/site_ruby", "/usr/lib/ruby/vendor_ruby/2.2.0", "/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.2.0", "/usr/lib/ruby/vendor_ruby", "/usr/lib/ruby/2.2.0", "/usr/lib/x86_64-linux-gnu/ruby/2.2.0"]bundler: failed to load command: mutant (/usr/local/bin/mutant)
LoadError: cannot load such file -- mutant/mutator/node
  /var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant.rb:92:in `require'
  /var/lib/gems/2.2.0/gems/mutant-0.8.12/lib/mutant.rb:92:in `<top (required)>'
  /var/lib/gems/2.2.0/gems/mutant-0.8.12/bin/mutant:8:in `require'
  /var/lib/gems/2.2.0/gems/mutant-0.8.12/bin/mutant:8:in `<top (required)>'
  /usr/local/bin/mutant:23:in `load'
  /usr/local/bin/mutant:23:in `<top (required)>'
```

**Comment by mbj** [comment]
@seza443 Can you post your `Gemfile` and `Gemfile.lock`?

**Comment by seza443** [comment]
[Gemfile](https://github.com/GeoHealth/HAppi_backend/blob/df93a2cd18b4ceb365f8e2e69fbaa6f9d6f24965/Gemfile) and [Gemfile.lock](https://github.com/GeoHealth/HAppi_backend/blob/df93a2cd18b4ceb365f8e2e69fbaa6f9d6f24965/Gemfile.lock)

**Comment by mbj** [comment]
@seza443 At the location of the print can you post the result of `p method(:require)` and `p method(:require).source_location`.

Right now I see:

* The gem is correctly installed
* The Gemfile contains mutant (transitively via `mutant-rspec` which is recommended as default)
* The `$LOAD_PATH` at the failing require is correctly set-up

Hence I conclude the require mechanism is overwritten by some gem that introduces the problem. It may even hide an exception on loading `mutant/mutator/node` and map this to `LoadError` falsely.

**Comment by seza443** [comment]
`p method(:require)` gives

```
#<Method: Object(Kernel)#require>
```

and `p method(:require).source_location` gives
```
nil
```

The machine where I'm running this must be mis-configured somehow because it works fine on Travis-CI and my other machine 🌵

**Comment by mbj** [comment]
The method does not appear to be overwritten.

> The machine where I'm running this must be mis-configured somehow because it works fine on Travis-CI and my other machine :cactus:

@seza443 interesting, can you delete and re-install the gem? It could be that the machine you are running has some FS issues that depending on the sequence of FS commands makes the file being found our not.

**Comment by seza443** [comment]
Hey it worked!

Well actually, I reinstalled by specifying the path: `bundle install --path vendor/bundle` and voilà! 😃 

Thank you @mbj

**Comment by mbj** [comment]
@seza443 I suspect you should now audit your FS and find and fix problems with it. IMO all your data is in risk. But thats not a topic for mutant as hopefully nobody does implement an FS (or anything non trivial) in Ruby anway :P

Closing this.
