### ISSUE TITLE
Overeager mutation of `#to_i` leads to `unparser` nil bomb

### ISSUE THREAD

**Issue by michaelherold** [mbj/mutant#738]
I have managed to reproduce this in a minimal example, but I am having a hard time finding where to add the test within Mutant and Unparser to contribute. I am happy to work on a fix if I can get some pointers on where to start!

## Reproduction

I made a reproduction script [here](https://github.com/michaelherold/mutant_to_i_bug) that you can pull down to see the bug in action.

Here's a quick way to pull down the reproduction:

    git clone git@github.com:michaelherold/mutant_to_i_bug.git
    cd mutant_to_i_bug
    ./run

For ease of reference, here is the code that causes the bug:

```ruby
class Foo
  EPOCH_TIME = 1_000

  def to_i
    1_528_771_800
  end

  def to_time
    Time.at(to_i + EPOCH_TIME)
  end
end
```

My guess is that [this mutator](https://github.com/mbj/mutant/blob/24f6d42fa2b3d30fbf206169d08383972c803242/lib/mutant/mutator/node/send.rb#L181-L188) is the one causing the bug. 

That lone call to `to_i` instead of `self.to_i` causes the error. If I change it to `self.to_i`, the mutation test runs to completion (and reports that I should remove the `self.` 😆 ).

## Stack Trace

Here is the top of the stack trace:

```
bundler: failed to load command: mutant (/Users/michael/.gem/ruby/2.4.2/bin/mutant)
NoMethodError: undefined method `type' for nil:NilClass
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:32:in `block in effective_arguments'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:31:in `each'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:31:in `each_with_index'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:31:in `each'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:31:in `map'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:31:in `effective_arguments'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:19:in `block in dispatch'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter.rb:185:in `parentheses'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter/send/arguments.rb:18:in `dispatch'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter.rb:104:in `write_to_buffer'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
  /Users/michael/.gem/ruby/2.4.2/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
  /Users/michael/.rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
  /Users/michael/.gem/ruby/2.4.2/gems/thread_safe-0.3.6/lib/thread_safe/cache.rb:56:in `fetch'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
  /Users/michael/.gem/ruby/2.4.2/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
  /Users/michael/.gem/ruby/2.4.2/gems/unparser-0.2.7/lib/unparser/emitter.rb:499:in `run'
```

**Comment by mbj** [comment]
@michaelherold But in unfortunate news, I'm super busy. Its very unlikely I can take a stab to fix that one "fast".

Mutants mutation tests in `meta` directory are relatively easy to extend, you can probably write a test that triggers the bug easily, and try a fix.

**Comment by michaelherold** [comment]
No worries on being busy, I totally understand! I will give it a shot to
fix it myself. Thank you for the pointers.
