### ISSUE TITLE
Syntactically incorrect mutation for lambda

### ISSUE THREAD

**Issue by pawelpacana** [mbj/mutant#802]
I've been playing with mutant from master branch and found that beginning from `d0ff655cbf3f8d37eecb863f6959291e3b33638d` mutant would produce following mutation:

```diff
@@ -1,6 +1,4 @@
-def initialize(clock: ->() do
-  Time.now.utc
-end)
+def initialize(clock: ->.utc)
   @clock = clock
 end
```

This is something incorrect in terms of syntax:

```
SyntaxError:
  /Users/pawelpacana/Code/mutant-bug/lib/lambda.rb:2: syntax error, unexpected '.', expecting keyword_do_LAMBDA or tLAMBEG
    def initialize(clock: ->.utc)
                            ^
  /Users/pawelpacana/Code/mutant-bug/lib/lambda.rb:9: syntax error, unexpected keyword_end, expecting end-of-input
```

The code to reproduce is at https://github.com/pawelpacana/mutant-bug.

**Comment by mbj** [comment]
@pawelpacana Thanks. Also note that mutant just merged a set of changes that will, with some other changes incoming, defend itself against emitting invalid syntax. The end goal is that only tests are allowed to kill mutations, no "other effects".

**Comment by pawelpacana** [comment]
I'm experiencing this now on 0.8.23 release,  see https://circleci.com/gh/RailsEventStore/rails_event_store/7288

Here's one of the examples:
```
RubyEventStore::Client#initialize:/Users/distiller/project/ruby_event_store/lib/ruby_event_store/client.rb:6
- rspec:49:./spec/client_spec.rb:9/RubyEventStore::Client publish returns self when success
- rspec:50:./spec/client_spec.rb:13/RubyEventStore::Client append returns client when success
- rspec:51:./spec/client_spec.rb:17/RubyEventStore::Client append to default stream when not specified
- rspec:52:./spec/client_spec.rb:22/RubyEventStore::Client publish to default stream when not specified
- rspec:53:./spec/client_spec.rb:27/RubyEventStore::Client delete_stream returns client when success
- rspec:54:./spec/client_spec.rb:31/RubyEventStore::Client publish to default stream when not specified
- rspec:55:./spec/client_spec.rb:36/RubyEventStore::Client publish first event, expect any stream state
- rspec:56:./spec/client_spec.rb:41/RubyEventStore::Client publish next event, expect any stream state
- rspec:57:./spec/client_spec.rb:48/RubyEventStore::Client publish first event, expect empty stream
- rspec:58:./spec/client_spec.rb:53/RubyEventStore::Client publish first event, fail if not empty stream
- rspec:59:./spec/client_spec.rb:60/RubyEventStore::Client publish event, expect last event to be the last read one
- rspec:60:./spec/client_spec.rb:67/RubyEventStore::Client publish event, fail if last event is not the last read one
- rspec:61:./spec/client_spec.rb:75/RubyEventStore::Client append many events
- rspec:62:./spec/client_spec.rb:84/RubyEventStore::Client read only up to page size from stream
- rspec:63:./spec/client_spec.rb:98/RubyEventStore::Client published event metadata will be enriched by metadata provided in with_metadata when executed inside a block
- rspec:64:./spec/client_spec.rb:109/RubyEventStore::Client published event metadata will not be enriched by metadata provided in with_metadata when published outside a block
- rspec:65:./spec/client_spec.rb:119/RubyEventStore::Client published event metadata will be enriched by nested metadata provided in with_metadata
- rspec:66:./spec/client_spec.rb:153/RubyEventStore::Client with_metadata is merged when nested
- rspec:67:./spec/client_spec.rb:176/RubyEventStore::Client event's  metadata takes precedence over with_metadata
- rspec:68:./spec/client_spec.rb:183/RubyEventStore::Client metadata is bound to the current instance and does not leak to others
- rspec:69:./spec/client_spec.rb:201/RubyEventStore::Client with_metadata is thread-safe
- rspec:70:./spec/client_spec.rb:213/RubyEventStore::Client timestamp can be overwritten by using with_metadata
- rspec:71:./spec/client_spec.rb:224/RubyEventStore::Client timestamp is utc time
- rspec:72:./spec/client_spec.rb:236/RubyEventStore::Client correlation_id and causation_id in metadata for sync handlers
- rspec:73:./spec/client_spec.rb:266/RubyEventStore::Client reading particular event
- rspec:74:./spec/client_spec.rb:271/RubyEventStore::Client reading non-existent event
- rspec:75:./spec/client_spec.rb:276/RubyEventStore::Client deprecation of read_event
- rspec:76:./spec/client_spec.rb:287/RubyEventStore::Client link events
- rspec:77:./spec/client_spec.rb:307/RubyEventStore::Client can handle protobuf event class instead of RubyEventStore::Event
- rspec:78:./spec/client_spec.rb:331/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:79:./spec/client_spec.rb:338/RubyEventStore::Client raise exception if event_id does not exist
- rspec:80:./spec/client_spec.rb:343/RubyEventStore::Client raise exception if event_id is not given or invalid
- rspec:81:./spec/client_spec.rb:348/RubyEventStore::Client fails when page size is invalid
- rspec:82:./spec/client_spec.rb:355/RubyEventStore::Client return all events ordered forward
- rspec:83:./spec/client_spec.rb:366/RubyEventStore::Client return specified number of events ordered forward
- rspec:84:./spec/client_spec.rb:376/RubyEventStore::Client return all events ordered backward
- rspec:85:./spec/client_spec.rb:387/RubyEventStore::Client return specified number of events ordered backward
- rspec:86:./spec/client_spec.rb:398/RubyEventStore::Client fails when starting event not exists
- rspec:87:./spec/client_spec.rb:408/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:88:./spec/client_spec.rb:413/RubyEventStore::Client successfully delete streams of events
- rspec:89:./spec/client_spec.rb:424/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:90:./spec/client_spec.rb:431/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:91:./spec/client_spec.rb:436/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:92:./spec/client_spec.rb:443/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:93:./spec/client_spec.rb:448/RubyEventStore::Client raise exception if stream name is incorrect
- rspec:94:./spec/client_spec.rb:453/RubyEventStore::Client return all events ordered forward
- rspec:95:./spec/client_spec.rb:465/RubyEventStore::Client return all events ordered backward
- rspec:96:./spec/client_spec.rb:477/RubyEventStore::Client return all events ordered forward
- rspec:97:./spec/client_spec.rb:486/RubyEventStore::Client return batch of events from the beginging ordered forward
- rspec:98:./spec/client_spec.rb:497/RubyEventStore::Client return batch of events from given event ordered forward
- rspec:99:./spec/client_spec.rb:508/RubyEventStore::Client return all events ordered backward
- rspec:100:./spec/client_spec.rb:518/RubyEventStore::Client return batch of events from the end ordered backward
- rspec:101:./spec/client_spec.rb:529/RubyEventStore::Client return batch of events from given event ordered backward
- rspec:102:./spec/client_spec.rb:539/RubyEventStore::Client fails when starting event not exists
- rspec:103:./spec/client_spec.rb:546/RubyEventStore::Client fails when page size is invalid
- rspec:104:./spec/client_spec.rb:555/RubyEventStore::Client create successfully event
- rspec:105:./spec/client_spec.rb:565/RubyEventStore::Client generate guid and create successfully event
- rspec:106:./spec/client_spec.rb:572/RubyEventStore::Client raise exception if expected version incorrect
- rspec:107:./spec/client_spec.rb:577/RubyEventStore::Client create event with optimistic locking
- rspec:108:./spec/client_spec.rb:591/RubyEventStore::Client expect no event handler is called
- rspec:109:./spec/client_spec.rb:601/RubyEventStore::Client expect publish to call event handlers
- rspec:110:./spec/client_spec.rb:611/RubyEventStore::Client expect publish to call event handlers
- rspec:111:./spec/client_spec.rb:621/RubyEventStore::Client create global event without stream name
- rspec:112:./spec/client_spec.rb:628/RubyEventStore::Client append fail if expected version is nil
- rspec:113:./spec/client_spec.rb:635/RubyEventStore::Client link fail if expected version is nil
- rspec:114:./spec/client_spec.rb:643/RubyEventStore::Client global stream is unordered, one cannot expect specific version number to work
- rspec:115:./spec/client_spec.rb:649/RubyEventStore::Client global stream is unordered, one cannot expect :none to work
- rspec:116:./spec/client_spec.rb:655/RubyEventStore::Client global stream is unordered, one cannot expect :auto to work
- rspec:117:./spec/client_spec.rb:661/RubyEventStore::Client only :none, :any, :auto and Integer allowed as expected_version
- rspec:118:./spec/client_spec.rb:674/RubyEventStore::Client only :none, :any, :auto and Integer allowed as expected_version when linking
- rspec:119:./spec/client_spec.rb:688/RubyEventStore::Client public read
- rspec:120:./spec/client_spec.rb:693/RubyEventStore::Client can load serialized event when using Default mapper
- rspec:121:./spec/client_spec.rb:712/RubyEventStore::Client can load serialized event using Protobuf mapper
- rspec:122:./spec/client_spec.rb:742/RubyEventStore::Client raise error when no subscriber
- rspec:123:./spec/client_spec.rb:809/RubyEventStore::Client #inspect
- rspec:124:./spec/client_spec.rb:750/RubyEventStore::Client#overwrite overwrites events data and metadata
- rspec:125:./spec/client_spec.rb:769/RubyEventStore::Client#overwrite overwrites event type
- rspec:126:./spec/client_spec.rb:784/RubyEventStore::Client#overwrite overwrites is chainable
- rspec:127:./spec/client_spec.rb:790/RubyEventStore::Client#streams_of 
- rspec:128:./spec/client_subscriptions_spec.rb:29/RubyEventStore::Client throws exception if subscriber is not defined
- rspec:129:./spec/client_subscriptions_spec.rb:34/RubyEventStore::Client throws exception if subscriber has not call method - handling subscribed events
- rspec:130:./spec/client_subscriptions_spec.rb:39/RubyEventStore::Client throws exception if subscriber has not call method - handling all events
- rspec:131:./spec/client_subscriptions_spec.rb:44/RubyEventStore::Client notifies subscribers listening on all events
- rspec:132:./spec/client_subscriptions_spec.rb:52/RubyEventStore::Client notifies subscribers listening on list of events
- rspec:133:./spec/client_subscriptions_spec.rb:62/RubyEventStore::Client notifies subscribers listening on all events - with lambda
- rspec:134:./spec/client_subscriptions_spec.rb:73/RubyEventStore::Client notifies subscribers listening on all events - with proc
- rspec:135:./spec/client_subscriptions_spec.rb:87/RubyEventStore::Client notifies subscribers listening on list of events - with lambda
- rspec:136:./spec/client_subscriptions_spec.rb:100/RubyEventStore::Client notifies subscribers listening on list of events - with proc
- rspec:137:./spec/client_subscriptions_spec.rb:112/RubyEventStore::Client allows to provide a custom dispatcher
- rspec:138:./spec/client_subscriptions_spec.rb:125/RubyEventStore::Client unsubscribes
- rspec:139:./spec/client_subscriptions_spec.rb:138/RubyEventStore::Client dynamic subscription
- rspec:140:./spec/client_subscriptions_spec.rb:150/RubyEventStore::Client subscribers receive event with enriched metadata
- rspec:141:./spec/client_subscriptions_spec.rb:162/RubyEventStore::Client throws exception if subscriber klass does not have call method - handling subscribed events
- rspec:142:./spec/client_subscriptions_spec.rb:168/RubyEventStore::Client throws exception if subscriber klass have not call method - handling all events
- rspec:143:./spec/client_subscriptions_spec.rb:174/RubyEventStore::Client dispatch events to subscribers via proxy
- rspec:144:./spec/client_subscriptions_spec.rb:185/RubyEventStore::Client dispatch all events to subscribers via proxy
- rspec:145:./spec/client_subscriptions_spec.rb:196/RubyEventStore::Client lambda is an output of global subscribe via proxy
- rspec:146:./spec/client_subscriptions_spec.rb:204/RubyEventStore::Client lambda is an output of subscribe via proxy
- rspec:147:./spec/client_subscriptions_spec.rb:212/RubyEventStore::Client dynamic global subscription via proxy
- rspec:148:./spec/client_subscriptions_spec.rb:229/RubyEventStore::Client notifies subscriber in the order events were published
- rspec:149:./spec/client_subscriptions_spec.rb:241/RubyEventStore::Client with many subscribers they are called in the order events were published
- rspec:150:./spec/client_subscriptions_spec.rb:262/RubyEventStore::Client subscribe unallowed calls
- rspec:151:./spec/client_subscriptions_spec.rb:281/RubyEventStore::Client dynamic subscribe v2 dynamic global subscription via proxy
- rspec:152:./spec/client_subscriptions_spec.rb:300/RubyEventStore::Client dynamic subscribe v2 dynamic subscription
- rspec:153:./spec/client_subscriptions_spec.rb:317/RubyEventStore::Client dynamic subscribe v2 nested dynamic subscription
- rspec:154:./spec/client_subscriptions_spec.rb:341/RubyEventStore::Client dynamic subscribe v2 dynamic subscription with exception
- rspec:155:./spec/client_subscriptions_spec.rb:357/RubyEventStore::Client dynamic subscribe v2 chained subscriptions
- rspec:593:./spec/within_spec.rb:7/RubyEventStore::Client subscribe with handler as object and block
- rspec:594:./spec/within_spec.rb:14/RubyEventStore::Client within without block
evil:RubyEventStore::Client#initialize:/Users/distiller/project/ruby_event_store/lib/ruby_event_store/client.rb:6:4714a
@@ -1,10 +1,8 @@
-def initialize(repository:, mapper: Mappers::Default.new, subscriptions: PubSub::Subscriptions.new, dispatcher: PubSub::Dispatcher.new, clock: ->() do
-  Time.now.utc
-end)
+def initialize(repository:, mapper: Mappers::Default.new, subscriptions: PubSub::Subscriptions.new, dispatcher: PubSub::Dispatcher.new, clock: ->.utc)
   @repository = repository
   @mapper = mapper
   @broker = PubSub::Broker.new(subscriptions: subscriptions, dispatcher: dispatcher)
   @clock = clock
   @metadata = Concurrent::ThreadLocalVar.new
 end
Killfork exited nonzero. Its result (if any) was ignored:
#<Process::Status: pid 1061 exit 1>
Killing the mutation resulted in an integration error.
This is the case when the tests selected for the current mutation
did not produce a test result, but instead an exception was raised.

This may point to the following problems:
* Bug in mutant
* Bug in the ruby interpreter
* Bug in your test suite
* Bug in your test suite under concurrency

The following exception was raised:

#<EOFError: end of file reached>
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/isolation/fork.rb:65:in `load'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/isolation/fork.rb:65:in `read_child_result'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/isolation/fork.rb:43:in `call'
/Users/distiller/.gem/ruby/2.5.1/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
/Users/distiller/.gem/ruby/2.5.1/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/isolation/fork.rb:133:in `block in call'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/isolation/fork.rb:132:in `pipe'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/isolation/fork.rb:132:in `call'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/env.rb:55:in `run_mutation_tests'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/env.rb:30:in `kill'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/parallel/worker.rb:62:in `call'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/parallel/worker.rb:62:in `handle_job'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/parallel/worker.rb:47:in `handle'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/parallel/worker.rb:33:in `run'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/parallel/worker.rb:19:in `run'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/parallel/master.rb:45:in `block (2 levels) in run'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.23/lib/mutant/actor/env.rb:16:in `block in spawn'
```

**Comment by mbj** [comment]
@pawelpacana Seems that this specific fix is not in 0.8.23. Can you check master?

**Comment by pawelpacana** [comment]
Oh, I did not notice the fix was outside 0.8.23 -- the timing of a release deceived me a bit. I'll check on master and let you know.

**Comment by mbj** [comment]
@pawelpacana I also thought the fix is part of 0.8.23, but turns out that the commit was later (according to GH).

**Comment by mbj** [comment]
@pawelpacana I just released mutant-0.8.24 from master. So your fix should be in.

**Comment by pawelpacana** [comment]
@mbj thanks! checked on 0.8.24 and this one is definitely fixed

I might have found another problem though, would report as separate issue when reproduced.

**Comment by mbj** [comment]
@pawelpacana I noticed increased crashes on 2.6.0, I suspect that we hit another MRI bug. See #830 where I finally make killfork log capture first class to ease debugging.
