### ISSUE TITLE
Syntactically incorrect mutation with block

### ISSUE THREAD

**Issue by pawelpacana** [mbj/mutant#837]
While [checking](https://circleci.com/gh/RailsEventStore/rails_event_store/7431?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 0.8.24 release I've noticed following issue: 

```
evil:RubyEventStore::Specification#in_batches:/Users/distiller/project/ruby_event_store/lib/ruby_event_store/specification.rb:124:dba97
@@ -1,7 +1,5 @@
 def in_batches(batch_size = DEFAULT_BATCH_SIZE)
-  Specification.new(reader, result.dup do |r|
-    r.read_as=:batch
-    r.batch_size=batch_size
-  end)
+  Specification.new(reader, r.read_as=:batch
+  r.batch_size=batch_size)
 end
Killfork exited nonzero. Its result (if any) was ignored:
#<Process::Status: pid 7470 exit 1>
Killing the mutation resulted in an integration error.
This is the case when the tests selected for the current mutation
did not produce a test result, but instead an exception was raised.

This may point to the following problems:
* Bug in mutant
* Bug in the ruby interpreter
* Bug in your test suite
* Bug in your test suite under concurrency

The following exception was raised:

#<EOFError: end of file reached>
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:65:in `load'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:65:in `read_child_result'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:43:in `call'
/Users/distiller/.gem/ruby/2.5.1/gems/procto-0.0.3/lib/procto.rb:62:in `public_send'
/Users/distiller/.gem/ruby/2.5.1/gems/procto-0.0.3/lib/procto.rb:62:in `block in initialize'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:133:in `block in call'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:132:in `pipe'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/isolation/fork.rb:132:in `call'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/env.rb:55:in `run_mutation_tests'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/env.rb:30:in `kill'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:62:in `call'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:62:in `handle_job'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:47:in `handle'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:33:in `run'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/parallel/worker.rb:19:in `run'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/parallel/master.rb:45:in `block (2 levels) in run'
/Users/distiller/.gem/ruby/2.5.1/gems/mutant-0.8.24/lib/mutant/actor/env.rb:16:in `block in spawn'
```

Reproduction: https://github.com/pawelpacana/mutant-bug-block/commit/e4f8b406df9a3e2e70483e457b863ea46a354890

**Comment by mbj** [comment]
@pawelpacana I suspect this is another crash of MRI that now gets correctly detected and not counted as a kill.

When mutant is OSS again #830 will help to debug this.

**Comment by pawelpacana** [comment]
> I suspect this is another crash of MRI

For the record, when manually mutated:
```diff
diff --git a/lib/specification.rb b/lib/specification.rb
index 5ce6ad0..0b5aa56 100644
--- a/lib/specification.rb
+++ b/lib/specification.rb
@@ -23,10 +23,8 @@ class Specification

   def with_something_else
     Specification.new(
-      Result.new.tap do |r|
         r.a = SomethingElse
         r.b = SomethingElse
-      end
     )
   end
```

this results in `SyntaxError`:                                                                                                                                                                                                                                          
```
$  bundle exec rspec                                                                                                                                                                                                                                                

An error occurred while loading ./spec/specification_spec.rb.
Failure/Error: require 'specification'

SyntaxError:
  /Users/pawelpacana/Code/mutant-bug-block/lib/specification.rb:27: syntax error, unexpected tIDENTIFIER, expecting ')'
          r.b = SomethingElse
          ^
  /Users/pawelpacana/Code/mutant-bug-block/lib/specification.rb:28: syntax error, unexpected ')', expecting keyword_end
      )
      ^
  /Users/pawelpacana/Code/mutant-bug-block/lib/specification.rb:36: syntax error, unexpected end-of-input, expecting keyword_end
# ./spec/specification_spec.rb:2:in `require'
# ./spec/specification_spec.rb:2:in `<top (required)>'
No examples found.


Finished in 0.00024 seconds (files took 0.06803 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by mbj** [comment]
> I suspect this is another crash of MRI

Well than this is a bug in mutant. anyhow I do want to make sure that mutant is able to present you that log message on each of these mutations.

**Comment by pawelpacana** [comment]
Thanks!
